#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import logging, xml.dom.minidom, config, utils, json, os, sys, glob
from template import KVMTemplate
logging.basicConfig(encoding='utf-8',level=logging.INFO, format='%(levelname)s: %(message)s') 
logger = logging.getLogger(__name__)

def usage():
    print(f'{sys.argv[0]} <name> <ipaddr> <arch>')
    exit(1)

if len(sys.argv) != 4:
    usage()
name = sys.argv[1]
ipaddr = sys.argv[2]
arch = sys.argv[3]
kvmhost = f'{name}'
host={'name':kvmhost, 'tpl':'domain.tpl','url':f'qemu+tls://{ipaddr}/system','arch':arch,'ipaddr':ipaddr,'sshport':22,'sshuser':'root' }
# devices = [fn.removesuffix(".tpl") for fn in os.listdir(config.DIR_DEVICE)]
devices = [fn.removesuffix(".tpl").removeprefix(f'{config.DIR_DEVICE}/') for fn in glob.glob(f'{config.DIR_DEVICE}/*.tpl')]
actions = [fn.removesuffix(".tpl") for fn in os.listdir(config.DIR_ACTION)]
devs=[]
for fn in devices:
    desc = ''
    with open(f'{config.DIR_DEVICE}/{fn}.tpl', 'r') as file:
        desc = file.readline().strip().replace("{#-", "").replace("{#", "").replace("#}", "")
    dev = {'kvmhost':kvmhost,'name':fn,'tpl': f'{fn}.tpl','desc':desc}
    dev['action'] = f'{dev["name"]}.action' if f'{dev["name"]}.action' in actions else ''
    doc = xml.dom.minidom.parseString(KVMTemplate(config.DIR_DEVICE ,f'{fn}.tpl').gen_xml())
    if doc.getElementsByTagName('interface').length > 0:
        dev['devtype'] = 'net'
    elif doc.getElementsByTagName('disk').length > 0:
        for disk in doc.getElementsByTagName('disk'):
            device = disk.getAttribute('device')
            if device in ['disk', 'cdrom']:
                dev['devtype'] = device
            else:
                logger.error(f'device unknown {dev}')
    else: 
        logger.error(f'device unknown {dev}')
    devs.append(dev)
json.dump(host, sys.stdout)
print()
json.dump(devs, sys.stdout, indent=4)
print()
