#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import config

ngx_cfg='''upstream flask_app {
    server 127.0.0.1:5009 fail_timeout=0;
    keepalive 64;
}
upstream websockify {
    server 127.0.0.1:6800;
    keepalive 64;
}
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 443 ssl;
    # # can modify to you websrv names
    # # .iso|\/meta-data|\/user-data must use ${META_SRV}
    server_name ${META_SRV};
    ssl_certificate     /etc/nginx/ssl/${META_SRV}.pem;
    ssl_certificate_key /etc/nginx/ssl/${META_SRV}.key;
    default_type application/json;
    location ~* .(favicon.ico)$ { access_log off; log_not_found off; add_header Content-Type image/svg+xml; return 200 '<svg width="104" height="104" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="104" height="104" rx="18" fill="url(#a)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M56 26a4.002 4.002 0 0 1-3 3.874v5.376h15a3 3 0 0 1 3 3v23a3 3 0 0 1-3 3h-8.5v4h3a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-21a2 2 0 0 1-2-2v-6a2 2 0 0 1 2-2h3v-4H36a3 3 0 0 1-3-3v-23a3 3 0 0 1 3-3h15v-5.376A4.002 4.002 0 0 1 52 22a4 4 0 0 1 4 4zM21.5 50.75a7.5 7.5 0 0 1 7.5-7.5v15a7.5 7.5 0 0 1-7.5-7.5zm53.5-7.5a7.5 7.5 0 0 1 0 15v-15zM46.5 50a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0zm14.75 3.75a3.75 3.75 0 1 0 0-7.5 3.75 3.75 0 0 0 0 7.5z" fill="#fff"/><defs><linearGradient id="a" x1="104" y1="0" x2="0" y2="0" gradientUnits="userSpaceOnUse"><stop stop-color="#34C724"/><stop offset="1" stop-color="#62D256"/></linearGradient></defs></svg>'; }
    error_page 403 = @403;
    location @403 { return 403 '{"code":403,"name":"lberr","desc":"Resource Forbidden"}'; }
    error_page 404 = @404;
    location @404 { return 404 '{"code":404,"name":"lberr","desc":"Resource not found"}'; }
    error_page 405 = @405;
    location @405 { return 405 '{"code":405,"name":"lberr","desc":"Method not allowed"}'; }
    error_page 502 = @502;
    location @502 { return 502 '{"code":502,"name":"lberr","desc":"backend server not alive"}'; }
    error_page 504 = @504;
    location @504 { return 504 '{"code":504,"name":"lberr","desc":"Gateway Time-out"}'; }
    # include /etc/nginx/http-enabled/jwt_sso_auth.inc;
    # # default page is guest ui
    location / { return 301 https://$server_name/guest.html; }
    location /tpl/ {
        # # proxy cache default is on, so modify host|device|gold, should clear ngx cache
        # auth_request @sso-auth;
        # host/device/gold can cached by proxy_cache default
        location ~* ^/tpl/(host|device|gold|iso)/ {
            if ($request_method !~ ^(GET)$ ) { return 405; }
            proxy_pass http://flask_app;
        }
        return 404;
    }
    location /vm/ {
        # auth_request @sso-auth;
        # # no cache!! mgr private access
        proxy_cache off;
        expires off;
        location ~* ^/vm/(ipaddr|blksize|desc|setmem|setcpu|list|start|reset|stop|delete|console|display|xml|ui|freeip)/ {
            if ($request_method !~ ^(GET)$ ) { return 405; }
            # # for server stream output
            proxy_buffering                    off;
            proxy_request_buffering            off;
            proxy_pass http://flask_app;
        }
        location ~* ^/vm/(create|attach_device|detach_device|cdrom)/ {
            if ($request_method !~ ^(POST)$ ) { return 405; }
            # # for server stream output
            proxy_buffering                    off;
            proxy_request_buffering            off;
            proxy_pass http://flask_app;
        }
        return 404;
    }
    location /websockify {
        # # /websockify used by admin & guest ui
        set $websockkey "${WEBSOCKKEY}";
        secure_link $arg_k,$arg_e;
        secure_link_md5 "$websockkey$secure_link_expires$arg_token$uri";
        if ($secure_link = "") { return 403; }
        if ($secure_link = "0") { return 410; }
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://websockify;
    }
    # # tanent api
    location /user/ {
        location ~* ^/user/vm/(list|start|reset|stop|console|display)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # no cache!! guest user api, guest private access
            proxy_cache off;
            expires off;
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(GET)$ ) { return 405; }
            rewrite ^/user(.*)$ $1 break;
            proxy_pass http://flask_app;
        }
        location ~* ^/user/vm/(cdrom)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # no cache!! guest user api, guest private access
            proxy_cache off;
            expires off;
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(POST)$ ) { return 405; }
            rewrite ^/user(.*)$ $1 break;
            proxy_pass http://flask_app;
        }
        location ~* ^/user/vm/(getiso)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # /tpl/iso need cache
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(GET)$ ) { return 405; }
            set $urieat '';
            # # just for eating uri -> /tpl/iso/,no args, can cache
            proxy_pass http://flask_app/tpl/iso/$urieat;
            # rewrite ^.*$ /tpl/iso/ break;
            # # /tpl/iso/?k=XtaHHDjE_nULHFdM2Dsupw&e=1745423940. with args, can not cache
            # proxy_pass http://flask_app;
        }
        return 403;
    }
    # # tanent user UI manager # #
    location = /guest.html { return 301 /ui/userui.html$is_args$args; }
    # # admin ui # #
    location = /admin.html { return 301 /ui/tpl.html; }
    # # static resource # #
    # # ui/term/spice/novnc use flask_app serve, add rewrite
    # rewrite ^ /public$uri break;proxy_pass http://flask_app;
    location /ui { alias ${OUT_DIR}/ui/; }
    location /term { alias ${OUT_DIR}/term/; }
    location /spice { alias ${OUT_DIR}/spice/; }
    location /novnc { alias ${OUT_DIR}/novnc/; }
    # # # # # # # # # # # # # # # # # # # # # # # # #
    # # only .iso|meta-data|user-data(include subdir resource)
    location ~* (\.iso|\/meta-data|\/user-data)$ { set $limit 0; root ${OUT_DIR}/cidata; }
    location ^~ /gold { set $limit 0; alias ${OUT_DIR}/gold/; }
    # /gold/uuid.iso => /gold/uuid.iso
    # /uuid.iso      => ${OUT_DIR}/iso/uuid.iso
}
server {
    listen 80;
    server_name ${META_SRV};
    location / { return 301 https://$server_name$request_uri$is_args$args; }
    # # only .iso|meta-data|user-data(include subdir resource)
    # rewrite ^ /public/iso$uri break; proxy_pass http://flask_app;
    location ~* (\.iso|\/meta-data|\/user-data)$ { set $limit 0; root ${OUT_DIR}/cidata; }
    location ^~ /gold { set $limit 0; alias ${OUT_DIR}/gold/; }
}
'''
ngx_cfg = ngx_cfg.replace('${META_SRV}', config.META_SRV)
ngx_cfg = ngx_cfg.replace('${WEBSOCKKEY}', config.WEBSOCKIFY_SECURE_LINK_MYKEY)
ngx_cfg = ngx_cfg.replace('${USERKEY}', config.USER_ACCESS_SECURE_LINK_MYKEY)
ngx_cfg = ngx_cfg.replace('${OUT_DIR}', config.OUTDIR)
with open('kvm.conf', "w") as file:
    file.write(ngx_cfg)
print(f'''
# kvm.conf
{config.OUTDIR}/gold   ==>   http(s) gold disk directory
{config.OUTDIR}/ui     ==>   static html/js.. directory
{config.OUTDIR}/term   ==>   static html/js.. directory
{config.OUTDIR}/spice  ==>   static html/js.. directory
{config.OUTDIR}/novnc  ==>   static html/js.. directory
{config.OUTDIR}/cidata ==>   dynamic iso/data directory
   LOCAL : ln -s ...../cidata {config.OUTDIR}/cidata
   REMOTE: sshfs {config.OUTDIR}/cidata ...../cidata
   NFS:.....
   inotify.sh, s3 ....
golds.json, sshfs/sshfs/ssh/http/local, (http/https curl convert -m1)
''')
