#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, config

ngx_cfg='''upstream flask_app {
    sticky;
    server 127.0.0.1:5009 fail_timeout=0;
    keepalive 64;
}
upstream websockify {
    sticky;
    server 127.0.0.1:6800;
    keepalive 64;
}
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 443 ssl;
    # # can modify to you websrv names
    # # \\.iso|\\/meta-data|\\/user-data must use ${META_SRV}
    server_name ${META_SRV};
    ssl_certificate     /etc/nginx/ssl/${META_SRV}.pem;
    ssl_certificate_key /etc/nginx/ssl/${META_SRV}.key;
    default_type application/json;
    error_page 403 = @403;
    location @403 { return 403 '{"code":403,"name":"lberr","desc":"Resource Forbidden"}'; }
    error_page 404 = @404;
    location @404 { return 404 '{"code":404,"name":"lberr","desc":"Resource not found"}'; }
    error_page 405 = @405;
    location @405 { return 405 '{"code":405,"name":"lberr","desc":"Method not allowed"}'; }
    error_page 502 = @502;
    location @502 { return 502 '{"code":502,"name":"lberr","desc":"backend server not alive"}'; }
    error_page 504 = @504;
    location @504 { return 504 '{"code":504,"name":"lberr","desc":"Gateway Time-out"}'; }
    ${AUTH}include /etc/nginx/http-enabled/jwt_sso_auth.inc;
    # # default page is guest ui
    location / { return 301 https://$server_name/guest.html; }
    location /tpl/ {
        # # proxy cache default is on, so modify host|device|gold, should clear ngx cache
        ${AUTH}auth_request @sso-auth;
        # host/device/gold can cached by proxy_cache default
        location ~* ^/tpl/(host|device|gold|iso)/ {
            if ($request_method !~ ^(GET)$ ) { return 405; }
            proxy_pass http://flask_app;
        }
        return 404;
    }
    location /vm/ {
        ${AUTH}auth_request @sso-auth;
        # # no cache!! mgr private access
        proxy_cache off;
        expires off;
        location ~* ^/vm/(ipaddr|blksize|netstat|desc|setmem|setcpu|list|start|reset|stop|delete|console|display|xml|ui|freeip)/ {
            if ($request_method !~ ^(GET)$ ) { return 405; }
            # # for server stream output
            proxy_buffering                    off;
            proxy_request_buffering            off;
            proxy_pass http://flask_app;
        }
        location ~* ^/vm/(create|attach_device|detach_device|cdrom)/ {
            if ($request_method !~ ^(POST)$ ) { return 405; }
            # # for server stream output
            proxy_buffering                    off;
            proxy_request_buffering            off;
            proxy_pass http://flask_app;
        }
        return 404;
    }
    location /websockify {
        # # /websockify used by admin & guest ui
        set $websockkey "${WEBSOCKKEY}";
        secure_link $arg_k,$arg_e;
        secure_link_md5 "$websockkey$secure_link_expires$arg_token$uri";
        if ($secure_link = "") { return 403; }
        if ($secure_link = "0") { return 410; }
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://websockify;
    }
    # # tanent api
    location /user/ {
        location ~* ^/user/vm/(list|start|reset|stop|console|display)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # no cache!! guest user api, guest private access
            proxy_cache off;
            expires off;
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(GET)$ ) { return 405; }
            rewrite ^/user(.*)$ $1 break;
            proxy_pass http://flask_app;
        }
        location ~* ^/user/vm/(cdrom)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # no cache!! guest user api, guest private access
            proxy_cache off;
            expires off;
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(POST)$ ) { return 405; }
            rewrite ^/user(.*)$ $1 break;
            proxy_pass http://flask_app;
        }
        location ~* ^/user/vm/(getiso)/(?<kvmhost>.*)/(?<uuid>.*) {
            # # /tpl/iso need cache
            set $userkey "${USERKEY}";
            secure_link $arg_k,$arg_e;
            secure_link_md5 "$userkey$secure_link_expires$kvmhost$uuid";
            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }
            if ($request_method !~ ^(GET)$ ) { return 405; }
            set $urieat '';
            # # just for eating uri -> /tpl/iso/,no args, can cache
            proxy_pass http://flask_app/tpl/iso/$urieat;
            # rewrite ^.*$ /tpl/iso/ break;
            # # /tpl/iso/?k=XtaHHDjE_nULHFdM2Dsupw&e=1745423940. with args, can not cache
            # proxy_pass http://flask_app;
        }
        return 403;
    }
    # # tanent user UI manager # #
    location = /guest.html { return 301 /ui/userui.html$is_args$args; }
    # # admin ui # #
    location = /admin.html { return 301 /ui/tpl.html; }
    location = /ui/tpl.html {
        ${AUTH}auth_request @sso-auth;
        alias ${OUT_DIR}/ui/tpl.html;
    }
    # # static resource # #
    # # ui/term/spice/novnc use flask_app serve, add rewrite
    # rewrite ^ /public$uri break;proxy_pass http://flask_app;
    location /ui { alias ${OUT_DIR}/ui/; }
    location /term { alias ${OUT_DIR}/term/; }
    location /spice { alias ${OUT_DIR}/spice/; }
    location /novnc { alias ${OUT_DIR}/novnc/; }
    # # # # # # # # # # # # # # # # # # # # # # # # #
    # # only .iso|meta-data|user-data(include subdir resource)
    location ~* (\\.iso|\\/meta-data|\\/user-data)$ { set $limit 0; root ${OUT_DIR}/cidata; }
    location ^~ /gold { set $limit 0; alias ${OUT_DIR}/gold/; }
    # /gold/uuid.iso => /gold/uuid.iso
    # /uuid.iso      => ${OUT_DIR}/iso/uuid.iso
}
server {
    listen 80;
    server_name ${META_SRV};
    location / { return 301 https://$server_name$request_uri$is_args$args; }
    # # only .iso|meta-data|user-data(include subdir resource)
    # rewrite ^ /public/iso$uri break; proxy_pass http://flask_app;
    location ~* (\\.iso|\\/meta-data|\\/user-data)$ { set $limit 0; root ${OUT_DIR}/cidata; }
    location ^~ /gold { set $limit 0; alias ${OUT_DIR}/gold/; }
}
'''
ngx_cfg = ngx_cfg.replace('${META_SRV}', config.META_SRV)
ngx_cfg = ngx_cfg.replace('${WEBSOCKKEY}', config.MYKEY_WEBSOCKIFY)
ngx_cfg = ngx_cfg.replace('${USERKEY}', config.MYKEY_CTRL_PANEL)
ngx_cfg = ngx_cfg.replace('${OUT_DIR}', config.OUTDIR)
ngx_cfg = ngx_cfg.replace('${AUTH}', '')
# ngx_cfg = ngx_cfg.replace('${AUTH}', '# ')
print(ngx_cfg)
print(f'''
{config.OUTDIR}/gold   ==>   http(s) gold disk directory
{config.OUTDIR}/ui     ==>   static html/js.. directory
{config.OUTDIR}/term   ==>   static html/js.. directory
{config.OUTDIR}/spice  ==>   static html/js.. directory
{config.OUTDIR}/novnc  ==>   static html/js.. directory
{config.OUTDIR}/cidata ==>   dynamic iso/data directory
   LOCAL : ln -s ...../cidata {config.OUTDIR}/cidata
   REMOTE: sshfs {config.OUTDIR}/cidata ...../cidata
   NFS:.....
   inotify.sh, s3 ....
golds.json, sshfs/sshfs/ssh/http/local, (http/https curl convert -m1)
''', file=sys.stderr)
