#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from sqlalchemy import func,text,Column,String,Integer,DateTime,Enum,ForeignKey
from config import config
import os

def load_file(file_path):
    if os.path.isfile(file_path):
        return open(file_path, "rb").read()
    raise Exception('file {} nofound'.format(file_path))

path = config.ISO_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
# # cdrom os install image dir
path = config.ISO_DIR + '/iso'
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.GOLD_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.ACTION_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.DEVICE_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.DOMAIN_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.META_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.TOKEN_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.NOCLOUD_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)
path = config.REQ_JSON_DIR
if not os.path.isdir(path):
    os.mkdir(path, 0o755)

print(r'VNC:{}, SPICE:{}'.format(config.VNC_DISP_URL, config.SPICE_DISP_URL))

# create tables if not exists
import database as db

db.Base.metadata.drop_all(db.engine)
db.Base.metadata.create_all(db.engine)

print('''
# # kvmhost
| name   | tpl           | url                                        | ipaddr      |sshport| arch   |
|--------+---------------+--------------------------------------------+-------------+-------+--------|
| host01 | newvm.vnc.tpl | qemu+tls://192.168.168.1/system            |192.168.168.1| 60022 | x86_64 |
| demo   | newvm.vnc.tpl | qemu+ssh://root@192.168.168.1:60022/system |192.168.168.1| 60022 | x86_64 |
# # kvmdevice
| kvmhost | name       | devtype | tpl                             | action                          | desc             |
|---------+------------+---------+---------------------------------+---------------------------------+------------------|
| host01  | local-disk | disk    | var.lib.libvirt.images.file.tpl | storage.lib.libvirt.images.file | 文件系统DISK     |
| host01  | rbd-disk   | disk    | armsite.rbd.tpl                 | armsite.rbd                     | RBD DISK         |
| host01  | net.br-ext | net     | net.br-ext.tpl                  |                                 | br-ext网桥       |
| host01  | debiso_x86 | iso     | cdrom.debian12.x86.tpl          |                                 | x86 debian安装CD |

# # kvmgold
| name     | arch    | tpl                        | desc                          |
| debian12 | x86_64  | bookworm.amd64.qcow2       | debian12 amd64 操作系统       |
| debian12 | aarch64 | bookworm.arm64.qcow2       | debian12 arm64 操作系统       |
| euler22  | x86_64  | openeuler2203.x86_64.qcow2 | openeuler 2203 amd64 操作系统 |
''')
hosts=[
    db.KVMHost(name='host01',tpl='newvm.vnc.tpl',url='qemu+tls://192.168.168.1/system',arch='x86_64',ipaddr='192.168.168.1',sshport=60022),
    db.KVMHost(name='demo',tpl='newvm.vnc.tpl',url='qemu+ssh://root@192.168.168.1:60022/system',arch='x86_64',ipaddr='192.168.168.1',sshport=60022),
]
host01_devs=[
    db.KVMDevice(kvmhost='host01',name='local-disk',devtype='disk',tpl='var.lib.libvirt.images.file.tpl',action='storage.lib.libvirt.images.file',desc='文件系统DISK'),
    db.KVMDevice(kvmhost='host01',name='rbd-disk',devtype='disk',tpl='armsite.rbd.tpl',action='armsite.rbd',desc='RBD DISK'),
    db.KVMDevice(kvmhost='host01',name='net.br-ext',devtype='net',tpl='net.br-ext.tpl',action='',desc='br-ext网桥'),
    db.KVMDevice(kvmhost='host01',name='debiso_x86',devtype='iso',tpl='cdrom.debian12.x86.tpl',action='',desc='debian安装CD'),
]
db.session.add_all(hosts)  # db.session.add(host01)
db.session.add_all(host01_devs)
db.session.commit()

golds=[
    db.KVMGold(name='',arch='x86_64',  tpl='',desc='数据盘'),
    db.KVMGold(name='',arch='aarch64', tpl='',desc='数据盘'),
    db.KVMGold(name='debian12',arch='x86_64', tpl='bookworm.amd64.qcow2',desc='debian12 amd64 操作系统'),
    db.KVMGold(name='debian12',arch='aarch64',tpl='bookworm.arm64.qcow2',desc='debian12 arm64 操作系统'),
    db.KVMGold(name='euler22',arch='x86_64', tpl='openeuler2203.x86_64.qcow2',desc='openeuler 2203 amd64 操作系统'),
]
db.session.add_all(golds)
db.session.commit()

kvm_arm_srv1_host = db.KVMHost(name='kvm-arm-srv1',tpl='newvm.vnc.tpl',url='qemu+ssh://root@10.170.24.2:60022/system',arch='aarch64',ipaddr='10.170.24.2',sshport=60022)
kvm_arm_srv1_devs=[
    db.KVMDevice(kvmhost="kvm-arm-srv1",name="rbd-disk",devtype="disk",tpl="armsite.rbd.tpl",action="armsite.rbd",desc="ARMSITE RBD DISK"),
    db.KVMDevice(kvmhost="kvm-arm-srv1",name="net.br-ext",devtype="net",tpl="net.br-ext.tpl",action="",desc="br-ext网桥"),
    db.KVMDevice(kvmhost="kvm-arm-srv1",name="debiso_arm",devtype="iso",tpl="cdrom.debian12.arm.tpl",action="",desc="arm debian安装CD"),
]
db.session.add(kvm_arm_srv1_host)
db.session.add_all(kvm_arm_srv1_devs)
db.session.commit()

kvm_x86_srv1_host = db.KVMHost(name='kvm-x86-srv1',tpl='newvm.vnc.tpl',url='qemu+ssh://root@10.170.24.20:60022/system',arch='x86_64',ipaddr='10.170.24.20',sshport=60022)
kvm_x86_srv1_devs=[
    db.KVMDevice(kvmhost="kvm-x86-srv1",name="rbd-disk",devtype="disk",tpl="x86site.rbd.tpl",action="x86site.rbd",desc="X86SITE RBD DISK"),
    db.KVMDevice(kvmhost="kvm-x86-srv1",name="net.br-ext",devtype="net",tpl="net.br-ext.tpl",action="",desc="br-ext网桥"),
    db.KVMDevice(kvmhost="kvm-x86-srv1",name="debiso_x86",devtype="iso",tpl="cdrom.debian12.x86.tpl",action="",desc="x86 debian安装CD")
]
db.session.add(kvm_x86_srv1_host)
db.session.add_all(kvm_x86_srv1_devs)
db.session.commit()

def file_exists(dirname, fn, msg):
    red='\033[31m'
    green='\033[32m'
    yellow='\033[33m'
    rst='\033[0m'
    if os.path.exists(os.path.join(dirname, fn)):
        print(f'  {green}SUCCESS{rst} ..{dirname[-15:]:15.15s}  --> {fn:20.20s} {green}OK{rst}')
        return True
    print(f'{yellow}{msg}{rst}')
    print(f'  {red}FAILED{rst}  ..{dirname[-15:]:15.15s}  --> {fn:20.20s} {red}NOFOUND{rst}')
    return False

for r in db.Base.exesql(f'select * from kvmhost'):
    file_exists(config.DOMAIN_DIR, r.tpl, f'{r.name:10.10s} {r.arch:8.8s}')
for dev in db.Base.exesql(f'select * from kvmdevice'):
    file_exists(config.DEVICE_DIR, dev.tpl, f'{dev.devtype:5.5s} {dev.name}')
    if dev.action is not None and len(dev.action) != 0:
        file_exists(config.ACTION_DIR, dev.action, f'{dev.devtype:5.5s} {dev.name}')
    elif dev.devtype == 'disk' or dev.devtype == 'iso':
        content = load_file(os.path.join(config.DEVICE_DIR, dev.tpl))
        print(content.decode('utf-8'))

for gold in db.Base.exesql(f'select * from kvmgold'):
    file_exists(config.GOLD_DIR, gold.tpl, f'{gold.name:10.10s} {gold.arch:8.8s} {gold.desc}')

file_exists(config.META_DIR, 'meta_data', f'meta_data')
file_exists(config.META_DIR, 'user_data', f'user_data')

# sql="insert into tbl (name) values ('{name}')"
# dev={'name':'net'}
# db.Base.exesql(sql, **dev)

sql="select * from kvmhost"
results = db.Base.exesql(sql)
for r in results:
    print(f'{r.name:10s}|{r.arch:8s}|{r.tpl:10s}|{r.url:44s}|{r.desc}')
print('===================================')
sql="select * from kvmdevice order by kvmhost,devtype"
results = db.Base.exesql(sql)
for r in results:
    print(f'{r.devtype:4s}|{r.kvmhost:10s}|{r.name:10s}|{r.tpl:10s}|{r.desc}')
    #print(f'{r._asdict()}')
# results = db.Base.exesql('SELECT * FROM kvmhost join kvmdevice on kvmdevice.kvmhost = kvmhost.name')
# for r in results:
#     print(f'{r._asdict()}')
