#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import logging, os
from typing import Iterable, Optional, Set, Tuple, Union, Dict
logging.basicConfig(encoding='utf-8', level=logging.INFO, format='[%(funcName)s@%(filename)s(%(lineno)d)]%(name)s %(levelname)s: %(message)s')
logging.getLogger().setLevel(level=os.getenv('LOG', 'INFO').upper())
logger = logging.getLogger(__name__)

import config, jinja2
from jinja2 import meta as jameta

def get_variables(dirname, fn):
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(dirname))
    return jameta.find_undeclared_variables(env.parse(env.loader.get_source(env, fn)[0]))
def remove_reserved(varset):
    for key in ['vm_uuid','vm_arch','vm_create','vm_creater','META_SRV','vm_last_disk']:
        varset.discard(key)
    return varset

varset = get_variables(config.META_DIR, 'meta_data')
varset.update(get_variables(config.META_DIR, 'user_data'))
varset.update(get_variables(config.DOMAIN_DIR, 'newvm.vnc.tpl'))
remove_reserved(varset)
logger.info(f'create vm {varset}')

for fn in os.listdir(config.DEVICE_DIR):
    varset = remove_reserved(get_variables(config.DEVICE_DIR, fn))
    logger.info(f'{fn.removesuffix(".tpl")} {varset}')
