#!/usr/bin/python3 -B
# -*- coding: utf-8 -*-

import logging, os, config
from typing import Iterable, Optional, Set, Tuple, Union, Dict
logging.basicConfig(encoding='utf-8', level=logging.INFO, format='[%(funcName)s@%(filename)s(%(lineno)d)]%(name)s %(levelname)s: %(message)s')
logging.getLogger().setLevel(level=os.getenv('LOG', 'INFO').upper())
logger = logging.getLogger(__name__)

from template import get_variables
varset = get_variables(config.DIR_DOMAIN, 'domain.tpl')
meta_varset=set()
for file in [fn for fn in os.listdir(config.DIR_META) if fn.endswith('.tpl')]:
    meta_varset.update(get_variables(config.DIR_META, file))
varset.update(meta_varset)
logger.info(f'create vm {varset}')
logger.info(f'meta {meta_varset}')

for fn in os.listdir(config.DIR_DEVICE):
    dev_varset = get_variables(config.DIR_DEVICE, fn)
    varset.update(dev_varset)
    logger.info(f'{fn.removesuffix(".tpl")} {dev_varset}')

logger.info(f'ALL {varset}')
