#!/bin/sh
ip link set $IFNAME address $MAC mtu $MTU up
[ $NODENAME = dl  ] &&    ip addr add 10.0.1.1 dev $IFNAME
[ $NODENAME = bj ] &&     ip addr add 10.0.1.2 dev $IFNAME
[ $NODENAME = pc ] &&     ip addr add 10.0.1.3 dev $IFNAME
[ $NODENAME = vps ] &&    ip addr add 10.0.1.4 dev $IFNAME
[ $NODENAME = asus ] &&   ip addr add 10.0.1.5 dev $IFNAME
[ $NODENAME = laptop ] && ip addr add 10.0.1.6 dev $IFNAME
ip route add 10.0.1.0/24 dev $IFNAME
# iptables -t nat -D POSTROUTING -s 10.0.1.0/24 -j MASQUERADE
# iptables -t nat -A POSTROUTING -s 10.0.1.0/24 -j MASQUERADE
