#!/bin/sh
ip link set $IFNAME address $MAC mtu $MTU up
[ $NODENAME = dl  ] && ip addr add 10.0.1.1 dev $IFNAME
[ $NODENAME = sy ] && ip addr add 10.0.1.2 dev $IFNAME
[ $NODENAME = laptop ] && ip addr add 10.0.1.3 dev $IFNAME
[ $NODENAME = home ] && ip addr add 10.0.1.4 dev $IFNAME
ip route add 10.0.1.0/24 dev $IFNAME
sysctl net.ipv4.ip_forward=1
iptables -t nat -D POSTROUTING -s 10.0.1.0/24 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.0.1.0/24 -j MASQUERADE
