---
- name: Check requirements
  package:
    name:
      - python3-libvirt
    state: present
  become: yes

- name: "Check if variable is defined"
  fail:
    msg: "variable item not passed"
  when: "item is not defined"
  loop:
  - vm_uuid

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Create VM if not exists
  block:

  - include: libvirt_vol.yml local_img="{{ base_image_name }}" tgt_pool="{{ libvirt_pool_name }}" tgt_vol="{{ vm_name }}-{{ vm_uuid }}" capacity={{vm_disk_mb}}

  - name: Define vm {{ vm_name }}-{{ vm_uuid }}
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', '{{ xml_template }}') }}"
  when: "vm_name not in existing_vms.list_vms"

- name: Start vm {{ vm_name }}-{{ vm_uuid }}
  community.libvirt.virt:
    name: "{{ vm_name }}-{{ vm_uuid }}"
    command: start

- name: Check VM is started
  community.libvirt.virt:
    name: "{{ vm_name }}-{{ vm_uuid }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 10
  delay: 3
