#!/usr/bin/env bash
LC_ALL=C
LANG=C
set -o nounset -o pipefail -o errexit
set -o xtrace
readonly DIRNAME="$(readlink -f "$(dirname "$0")")"
RBD_SECRET="id=admin:conf=${DIRNAME}/x86site.conf:keyring=${DIRNAME}/x86site.client.admin.keyring"
# # rbd pool name
DIR='libvirt-pool'
# # reqire: jq qemu-img cat
log() { echo "qemu-rbd.action $*"; }
str_equal() {
    [ "${1:-x}" == "${2:-y}" ]
}
json_config_default() {
    local key=${1}
    local default=${2}
    local str=""
    [ $# = 2 ] && {
        str="$(cat)"
    } || {
        str="$(cat ${3:?json_config input err})"
    }
    jq -r '('${key}') // "'${default}'"' <<< ${str}
}

REQ_JSON=$(cat)
URL=${URL:-}
TYPE=${TYPE:-}
HOSTIP=${HOSTIP:-}
SSHPORT=${SSHPORT:-}
SSHUSER=${SSHUSER:-}
log "${TYPE} ${URL} ${HOSTIP} ${REQ_JSON}"
UUID=$(printf "%s" "${REQ_JSON}" | json_config_default ".vm_uuid" "")
SIZE=$(printf "%s" "${REQ_JSON}" | json_config_default ".size" "10")G
GOLD=$(printf "%s" "${REQ_JSON}" | json_config_default ".gold" "")
char=$(printf "%s" "${REQ_JSON}" | json_config_default ".vm_last_disk" "")
BUS=$(printf "%s" "${REQ_JSON}" | json_config_default ".vm_disk_bus" "")
# # rbd pool name
DISK="${DIR}/vd${char}-${UUID}.raw"
str_equal "${BUS}" "ide"  && DISK="${DIR}/hd${char}-${UUID}.raw"
str_equal "${BUS}" "scsi" && DISK="${DIR}/sd${char}-${UUID}.raw"
str_equal "${BUS}" "sata" && DISK="${DIR}/sd${char}-${UUID}.raw"

[ -z "${GOLD}" ] && {
    qemu-img create -f raw rbd:${DISK}:${RBD_SECRET} ${SIZE}
} || {
    timeout 5m qemu-img convert -p -f qcow2 -W -m1 -O raw ${GOLD} rbd:${DISK}:${RBD_SECRET}
    # skip resize error, when SIZE < gold image size, error but now image uploaded! so skip error
    qemu-img resize -f raw rbd:${DISK}:${RBD_SECRET} ${SIZE} || true
}
exit 0
